### Create new user
# POST http://localhost:5000/register
# Content-Type: application/json

# {
#   "name": "a1",
#   "email": "a1@gmail.com",
#   "password": "aA123456",
#   "role": "admin",
#   "number": "12343212211"
# },


GET http://localhost:5000/categories
Content-Type: application/json



GET http://localhost:5000/programs
Content-Type: application/json



GET  http://localhost:5000/categories
Content-Type: application/json

{
  "nameEn": "category1",
  "nameAr": "فئة1",
  "type": "Incoming",
  "descriptionEn": "frist category",
  "descriptionAr": "الفئة الأولى",
  "isActive": true
}