## Create new user
# GET  http://localhost:5000/country-category/egypt
# Content-Type: application/json


GET  http://localhost:5000/category/6981fe7ed188377ff3917b6c
Content-Type: application/json


POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "name": "a2",
  "email": "a2@gmail.com",
  "password": "Aa123456",
  "number": "112322323"
}


