### Create new user
POST http://localhost:5000/register
Content-Type: application/json

{
  "name": "a1",
  "email": "a1@gmail.com",
  "password": "aA123456",
  "role": "admin",
  "number": "12343212211"
}
